name: Tests

on: pull_request

env:
  RUBY_VERSION: 3.2.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: postgres

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Setup RSpec
        run: |
          [ -f Gemfile ] && bundle
          gem install --no-document rspec -v '>=3.0, < 4.0'
      - name: Install PostgreSQL 12 client
        run: |
          sudo apt-get -yqq install libpq-dev
      - name: Run Tests
        env:
          PG_DATABASE: postgres
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: password
          RAILS_ENV: test
          WITH_COVERAGE: true
          DISABLE_SPRING: 1
        run: |
          bin/rails db:setup
          bundle exec rake test
      - name: RSpec Report
        run: rspec --force-color --format documentation