name: Tests

on: pull_request

env:
  RUBY_VERSION: 3.2.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: postgres

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Setup RSpec
        run: |
          [ -f Gemfile ] && bundle
          gem install --no-document rspec -v '>=3.0, < 4.0'
      - name: Setup database
        run: |
          rails db:create RAILS_ENV=test
          rails db:migrate RAILS_ENV=test
      - name: RSpec Report
        run: rspec --force-color --format documentation